---
name: Lint Code Base

defaults:
  run:
    shell: bash

on:
  push:
    branches-ignore: [main, develop]
  pull_request:

jobs:
  perltidy:
    name: Run perltidy on Perl Files
    runs-on: ubuntu-22.04
    container:
      image: perl:5.34
    steps:
      - uses: actions/checkout@v3
      - name: perl -V
        run: perl -V
      - name: Install dependencies
        run: cpanm -n Perl::Tidy@20220613
      - name: perltidy --version
        run: perltidy --version
      - name: Run perltidy
        shell: bash
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          shopt -s extglob globstar nullglob
          perltidy --pro=./.perltidyrc -b -bext='/' ./**/*.p[lm] ./**/*.t && git diff --exit-code
